'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('safetyToken')||'';
sessionStorage.setItem('safetyToken',token);history.replaceState(null,'',location.pathname);
let state={}, event='', index=0, frames=0, fps=8, playing=false, marks=[], busy=false, liveURL=null;
const tell=x=>{$('message').textContent=x;};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'X-Safety-Token':token,...options.headers}});if(!r.ok)throw Error((await r.json()).error||String(r.status));return r;}
async function command(payload){if(busy)return;tell('等待服务确认…');busy=true;try{const r=await api('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json();tell(result.message||result.error||'已返回');if(result.ok&&payload.action==='SUBMIT_REVIEW'){marks=[];$('marks').textContent='0 帧已标注';$('reviewForm').reset();}return result;}catch(e){tell(e.message);}finally{busy=false;}}
async function loadFrame(){if(!event)return;try{const r=await api('/api/frame?event='+encodeURIComponent(event)+'&index='+index);const p=await r.json();frames=p.frames;fps=p.fps||8;const bytes=Uint8Array.from(atob(p.jpeg),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}));const old=$('clip').src;$('clip').src=url;if(old.startsWith('blob:'))URL.revokeObjectURL(old);$('clip').hidden=false;$('clipEmpty').hidden=true;$('scrub').max=String(Math.max(0,frames-1));$('scrub').value=String(index);$('frameInfo').textContent=`${index+1} / ${frames} · ${(index/fps).toFixed(2)} s`;}catch(e){playing=false;frames=0;$('clip').hidden=true;$('clipEmpty').hidden=false;$('clipEmpty').textContent=e.message;}}
$('events').onchange=async()=>{playing=false;event=$('events').value;index=0;marks=[];$('marks').textContent='0 帧已标注';$('reviewForm').reset();if(event){await command({action:'SELECT_EVENT',event_id:event});await loadFrame();}};
$('prev').onclick=()=>{index=Math.max(0,index-1);loadFrame();};$('next').onclick=()=>{index=Math.min(Math.max(0,frames-1),index+1);loadFrame();};$('play').onclick=()=>{playing=!playing;};$('scrub').oninput=()=>{playing=false;index=Number($('scrub').value);loadFrame();};
$('mark').onclick=()=>{if(!event||!frames)return tell('请先选择可回放片段');marks=marks.filter(m=>m.frame_index!==index);marks.push({frame_index:index,offset_ms:Math.round(index/fps*1000),hands:[{side:'UNKNOWN',zone:$('hand').value}],material_occluded:$('occluded').checked});$('marks').textContent=marks.length+' 帧已标注';tell('当前帧已加入草稿；提交审核后才保存。');};
$('reviewForm').onsubmit=async e=>{e.preventDefault();if(!event)return tell('请先选择事件');const level=document.querySelector('input[name=level]:checked');if(!level)return;await command({action:'SUBMIT_REVIEW',event_id:event,review_level:Number(level.value),hand_zone:$('hand').value,primary_action:$('action').value,material_occluded:$('occluded').checked,notes:$('notes').value,frame_annotations:marks});};
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>command({action:b.dataset.action,event_id:event,expected_level:Number($('expected').value)});
$('approve').onclick=()=>{if(confirm('批准建议仅在下次视觉引擎启动后生效，仍需现场复测。是否继续？'))command({action:'APPLY_THRESHOLDS',explicit_approval:true,approved_by:'local_safety_officer'});};
async function refresh(){try{state=await(await api('/api/state')).json();$('service').textContent=state.fresh?state.service_state:'服务不可用 / STALE';$('mode').textContent=state.input_mode?.mode||'UNKNOWN';$('pending').textContent=state.pending_count??'—';$('reviewed').textContent=state.reviewed_today??'—';$('riskState').textContent=state.vision?.state||'UNCERTAIN';$('riskScore').textContent=state.vision?.risk_score??'—';$('stats').textContent=JSON.stringify(state.statistics||{},null,2);$('proposal').textContent=JSON.stringify(state.threshold_proposal||{status:'INSUFFICIENT_DATA',message:'需真实标注数据，不能自动修改参数'},null,2);$('approve').disabled=state.threshold_proposal?.status!=='PROPOSED';const rows=state.queue||[];const opts=rows.map(r=>({value:r.event_id,text:`${r.time||''} · ${r.system_state} · ${r.queue_status}`}));const signature=JSON.stringify(opts);if($('events').dataset.signature!==signature){$('events').replaceChildren(new Option('请选择事件',''),...opts.map(o=>new Option(o.text,o.value)));$('events').value=event;$('events').dataset.signature=signature;}const row=rows.find(r=>r.event_id===event);$('eventInfo').textContent=row?`评分 ${row.risk_score} · 证据 ${row.clip_status} · ${row.station}`:'选择事件查看片段';if(!busy&&$('message').textContent==='等待服务连接…')tell(state.last_result?.message||'已连接');}catch(e){$('service').textContent='OFFLINE';tell(e.message);}setTimeout(refresh,1000);}
async function refreshImage(){try{const r=await api('/api/image');const url=URL.createObjectURL(await r.blob());$('live').src=url;$('live').hidden=false;$('liveEmpty').hidden=true;if(liveURL)URL.revokeObjectURL(liveURL);liveURL=url;}catch(e){$('live').hidden=true;$('liveEmpty').hidden=false;}setTimeout(refreshImage,200);}
async function playback(){if(playing&&frames){index=(index+1)%frames;await loadFrame();}setTimeout(playback,1000/Math.max(1,fps));}refresh();refreshImage();playback();
